### ISSUE TITLE
Add xd-json-wrapper to Utility Libraries

### ISSUE THREAD

**Issue by svschannak** [AdobeXD/xd-awesome#14]
Until now there is no easy way to use ```JSON.stringify()```on nodes, artboards or the rootDocument. This library will change this behaviour with its wrapper classes.

You can use them the following way:
### getXDWrapper

This wrapper wraps any node object on an artboard and makes it suitable for json. It also returns all parent elements.

#### Example
```javascript
import { getXDWrapper } = "xd-json-wrapper";

const node = // use an actual node from an artboard in XD here
const wrappedNode = getXDWrapper(node);

const json = wrappedNode.toJSON();
// or
JSON.stringify(wrappedNode);
```

### getArtboardAsJSON

This wrapper wraps any artboard object and makes it suitable for json. It als returns all children nodes.

#### Example
```javascript
import { getArtboardAsJSON } = "xd-json-wrapper";

const artboard = // use an actual node from an artboard in XD here
const wrappedArtboard = getArtboardAsJSON(artboard);

const json = wrappedArtboard.toJSON();
// or
JSON.stringify(wrappedArtboard);
```

### getDocumentAsJSON

This wrapper wraps the complete XD document and returns a list of all artboards and their childrend nodes.

#### Example
```javascript
import { getDocumentAsJSON } = "xd-json-wrapper";

const documentRoot = // use an actual node from an artboard in XD here
const wrappedArtboard = getDocumentAsJSON(documentRoot);

const json = documentRoot.toJSON();
// or
JSON.stringify(documentRoot);
```

**Comment by kerrishotts** [comment]
Merged in :-) Thanks for the submission.
