### ISSUE TITLE
XD Starter Template project with live reload, types, and prettier

### ISSUE THREAD

**Issue by tato123** [AdobeXD/xd-awesome#22]
# Submit your project for inclusion in XD-Awesome

Hey! We're happy you want to submit your project to XD-Awesome. Please ensure that you use the following template:

## **Name of your project or content**
xd-starter-template

**Description of your project:** A _short_ description of your project or content

XD Template project is a cloneable javascript starter template. It provides a custom webpack plugin and comes pre-paged with support for types and typescript. The custom webpack plugin uses xdpm under the hood to provide live reload. It also includes prettier to ensure code is consistently styled. 

**Link to your project:** the link to your project or content

https://github.com/tato123/xd-template-project

**License:** the license of your project or content (must be open source)

MIT

**Category:** the category you want the project listed under

Template

## Why is it awesome?

_Tell us a little more about your project and why it would be great for inclusion in XD-Awesome._

It comes pre-packaged with everything you need to get started building an xd plugin in less than a couple minutes and immediately start seeing changes.

**Comment by kerrishotts** [comment]
Awesome -- this would be a great addition :-) Please submit a PR and we'll merge it in.

**Comment by dkstevekwak** [comment]
@tato123 Please feel free to create a PR for this. Note that there is a new PR template now.
