### ISSUE TITLE
xdpm webpack plugin

### ISSUE THREAD

**Issue by tato123** [AdobeXD/xd-awesome#23]
# Submit your project for inclusion in XD-Awesome

Hey! We're happy you want to submit your project to XD-Awesome. Please ensure that you use the following template:

## xdpm-webpack-plugin

**Description of your project:** 

On webpack build xd plugins are automatically synced to adobe xd development folder via xdpm

**Link to your project:** the link to your project or content
[https://github.com/tato123/xdpm-webpack-plugin](https://github.com/tato123/xdpm-webpack-plugin)

**License:** the license of your project or content (must be open source)
MIT

**Category:** the category you want the project listed under
Developer tools

## Why is it awesome?
Improves developer efficiency, with this plugin you can save a file and while running `webpack --watch` Adobe XD is always in sync with the latest version of the code

**Comment by kerrishotts** [comment]
Sweet :-) Please file a PR and we'll merge it to the repo (If you want to do both #22 and this in the same PR, that's fine, since they are somewhat related).

**Comment by dkstevekwak** [comment]
@tato123 Please feel free to create a PR for this. Note that there is a new PR template now. Closing the issue now.
