### ISSUE TITLE
Utility library: xd-localization-helper (MIT-Licensed)

### ISSUE THREAD

**Issue by pklaschka** [AdobeXD/xd-awesome#24]
# Submit your project for inclusion in XD-Awesome

Hey! We're happy you want to submit your project to XD-Awesome. Please ensure that you use the following template:

## **xd-localization-helper**

**Description of your project:** A small helper library making it easier for developers to add localization (for dialogs) to their plugins

**Link to your project:** https://github.com/pklaschka/xd-localization-helper

**License:** MIT

**Category:** Utility Libraries

## Why is it awesome?

It makes internationalization extremely easy (also allowing the usage of editors like [BabelEdit](https://www.codeandweb.com/babeledit) to manage many translations) and is as similar as it can be to the localization inside a `manifest.json` (having a default string, ISO 639-1 language codes etc.)

Also, it is very easy to integrate since it only requires copying one file or (if one uses npm) running `npm i xd-localization-helper` :wink:

Last, but not least, it allows configuration of the localization to – e.g. – force a certain language to be used if it's set in a plugin's preferences, making it easy to adjust to fit a plugin's needs.

**Comment by dkstevekwak** [comment]
closing this issue - covered in https://github.com/AdobeXD/xd-awesome/pull/28
