### ISSUE TITLE
uiLogos - XD plugin

### ISSUE THREAD

**Issue by realvjy** [AdobeXD/xd-awesome#25]
# Submitting uiLogos for inclusion in XD-Awesome

## **uiLogos**
Now you can quickly place dummy logos into Adobe XD. Plugin have more than 25+ professionally designed logos.

I'm very happy to announce initial version of this plugin for Adobe XD- uiLogos.

**Link to your project:** https://github.com/realvjy/uilogos-XD

**License:** MIT

**Category:** data

## Why is it awesome?
Sometime we all need professional logo as placeholder, and don't have time to create some dummy logos. uiLogos will solve this problem and you can directly insert logos in your mockup

**Comment by realvjy** [comment]
@ashryanbeats Can you please check this plugin and include in XD-Awesome

Thanks in advance

**Comment by dkstevekwak** [comment]
Hi @realvjy. This is an awesome plugin. Could you create a pull request for this? We now have a slightly modified PR submission process. Thank you!

**Comment by realvjy** [comment]
Open a PR. Closing this
