### ISSUE TITLE
xd-plugin-boilerplate

### ISSUE THREAD

**Issue by pklaschka** [AdobeXD/xd-awesome#26]
# Submit your project for inclusion in XD-Awesome

Hey! We're happy you want to submit your project to XD-Awesome. Please ensure that you use the following template:

## **xd-plugin-boilerplate (Adobe XD plugin boilerplate)**

**Description of your project:** A boilerplate with preconfigured ESLint, typings for autocompletion and Webpack (to support npm modules) for plugins.

**Link to your project:** https://github.com/pklaschka/xd-plugin-boilerplate

**License:** MIT

**Category:** Templates

## Why is it awesome?

It is an inspired by, but slightly optimized version of the template I use for my plugins. Additionally, with Webpack, ESLint and the typings (for JS autocompletion) being preconfigured, it has all the basic things that I (from my personal experience) find useful during plugin development. Though it is a bit similar to the one from #22, it is a bit more "light-weight" (with fewer dependencies), leaving a few more choices up to the developer, and therefore shouldn't be seen as a competitor, but merely as an alternative which leaves every developer the choice of which style he/she prefers.

Last, but not least, since I'm also the developer of the typescript definitions (https://github.com/AdobeXD/typings), autocompletion is where the template scores. It will always be kept up to date (when I update the typings, I update the template) and focuses on having a good autocompletion configured out of the box (with instructions regarding the different IDEs supported by the definitions etc.).

**Comment by dkstevekwak** [comment]
closing this issue - covered in https://github.com/AdobeXD/xd-awesome/pull/29
