### ISSUE TITLE
Wireframe Print Template

### ISSUE THREAD

**Issue by agnelnieves** [AdobeXD/xd-awesome#3]
Hello, Been using Adobe XD for the past 7 months and I'm loving it. I'd love to start contributing to its development. I'd like to start by adding a Wireframes template for paper prototyping. I'm planning to create a few utility plugins in the future.

**Comment by ashryanbeats** [comment]
Thanks for your interest @agnelnieves! 

This repo is for linking back to third-party developer resources for learning and using the APIs. 

Since this isn't an issue report for the XD Awesome repo, I'll close the issue.
