### ISSUE TITLE
Awesome-like logo idea

### ISSUE THREAD

**Issue by takidelfin** [AdobeXD/xd-awesome#4]
All awesome lists that I know have got an [awesome](https://awesome.re/)-style logo (or *awesome* badge at least)
So I tried to make something simple (in XD of course 😄)

---
![svg-image-from-gist](https://gist.githubusercontent.com/takidelfin/00f9bd787edabc9f4526808abf636969/raw/42144d029ea44a5e2d6d68099ddc339b3b82347e/xdawesome.svg?sanitize=true)

**Comment by ashryanbeats** [comment]
So cool! Do you want to submit a PR and put this in the readme, or shall I? Either way is good.

**Comment by takidelfin** [comment]
@ashryanbeats pull request sent! #5

**Comment by ashryanbeats** [comment]
Thank you! It would be awesome if you were to push your source XD file to a repo (perhaps with an MIT license) as well. We could then link to your repo from XD Awesome.

**Comment by takidelfin** [comment]
@ashryanbeats there it is: https://github.com/takidelfin/xd-awesome-logo/
:smile:

**Comment by ashryanbeats** [comment]
Thanks for doing this @takidelfin! So cool to see.
