### ISSUE TITLE
Links are not working.

### ISSUE THREAD

**Issue by midorikocak** [AdobeXD/xd-awesome#44]
All of the github links with paolobiagini name are gone due to 404.

**Comment by pklaschka** [comment]
Just FYI:
I've just wrote a PM to Paolo in the developer forums, making him aware of this and asking what's going on with his GitHub account (before everyone does the same, I just wanted to put this info in here; should he actually currently be unavailable on GitHub himself, I might be able to serve as a "voice" for him in this issue).

**Comment by pklaschka** [comment]
Ok. Paolo has allowed me to forward this information.

Paolo has (willingly) deleted his GitHub account in an effort to remove accounts he doesn't use (which, of course, unfortunately also affects this list). The plugins are also (for various reasons) no longer open-source, meaning it (according to him) might be better to remove them from the list.

I will now create a PR implementing this...

**Comment by ashryanbeats** [comment]
Aww, that's sad to hear. Hope Paolo's doing well! Thanks for taking this on @pklaschka.

**Comment by pklaschka** [comment]
@ashryanbeats Of course. He wrote that he's alright and just sorting out accounts he doesn't actively use as he has too many things to do (something I think most of us can relate to :slightly_smiling_face: )... So while I'm sad to see the list shrink, I have to pay him much respect for going an active step of reducing the amount of accounts. It's probably something many of us should do from time to time...
