### ISSUE TITLE
Add official resources

### ISSUE THREAD

**Issue by jlarmstrongiv** [AdobeXD/xd-awesome#46]
## Topic

This is an issue regarding:

- [x] The XD Awesome repository README.

## Description of the issue

Possible official resources that may be helpful
- https://github.com/AdobeXD/plugin-samples
- https://forums.adobexdplatform.com/
- https://adobexdplatform.com/plugin-docs/

**Comment by ashryanbeats** [comment]
Thanks @jlarmstrongiv! Feel free to submit a PR if you want to take this on. Otherwise, one of us can do it.

**Comment by jlarmstrongiv** [comment]
It’s exam week 😅sometime after that sure
