### ISSUE TITLE
Storage helper

### ISSUE THREAD

**Issue by pklaschka** [AdobeXD/xd-awesome#7]
I've open-sourced my storage helper, a small library making it easy to store and retrieve key-value-pair settings in plugins for Adobe XD. Since I used it in my plugins (and found it to be useful), I'd propose (again, something I created, so I may be a bit biased here – I have used it when building my plugins, however 😉) to add it in the category 'Utility Libraries'.

The repo is MIT-licensed and can be found here: https://github.com/pklaschka/xd-storage-helper

**Comment by kerrishotts** [comment]
Awesome :-) Please submit a PR and we'll pull it in.
