### ISSUE TITLE
Add `xdpm` to the list

### ISSUE THREAD

**Issue by pklaschka** [AdobeXD/xd-awesome#8]
I honestly don't even know what to write here. Since `xdpm` (https://github.com/AdobeXD/xdpm) is a repo in the AdobeXD GitHub organization, is an incredibly valuable tool for plugin developers and fits the category 'Developer Tools' perfectly, I think it is a must-have in this list (also, I don't feel as bad creating another proposal for one of my libraries if something else gets added to the list, as well 😉).

**Comment by kerrishotts** [comment]
;-)

Agree; I'll add it in :-)
